# coding: utf-8

"""
    CVAT REST API

    REST API for Computer Vision Annotation Tool (CVAT)  # noqa: E501

    OpenAPI spec version: v1
    Contact: nikita.manovich@intel.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PasswordChange(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "old_password": "str",
        "new_password1": "str",
        "new_password2": "str",
    }

    attribute_map = {
        "old_password": "old_password",
        "new_password1": "new_password1",
        "new_password2": "new_password2",
    }

    def __init__(
        self, old_password=None, new_password1=None, new_password2=None
    ):  # noqa: E501
        """PasswordChange - a model defined in Swagger"""  # noqa: E501
        self._old_password = None
        self._new_password1 = None
        self._new_password2 = None
        self.discriminator = None
        self.old_password = old_password
        self.new_password1 = new_password1
        self.new_password2 = new_password2

    @property
    def old_password(self):
        """Gets the old_password of this PasswordChange.  # noqa: E501


        :return: The old_password of this PasswordChange.  # noqa: E501
        :rtype: str
        """
        return self._old_password

    @old_password.setter
    def old_password(self, old_password):
        """Sets the old_password of this PasswordChange.


        :param old_password: The old_password of this PasswordChange.  # noqa: E501
        :type: str
        """
        if old_password is None:
            raise ValueError(
                "Invalid value for `old_password`, must not be `None`"
            )  # noqa: E501

        self._old_password = old_password

    @property
    def new_password1(self):
        """Gets the new_password1 of this PasswordChange.  # noqa: E501


        :return: The new_password1 of this PasswordChange.  # noqa: E501
        :rtype: str
        """
        return self._new_password1

    @new_password1.setter
    def new_password1(self, new_password1):
        """Sets the new_password1 of this PasswordChange.


        :param new_password1: The new_password1 of this PasswordChange.  # noqa: E501
        :type: str
        """
        if new_password1 is None:
            raise ValueError(
                "Invalid value for `new_password1`, must not be `None`"
            )  # noqa: E501

        self._new_password1 = new_password1

    @property
    def new_password2(self):
        """Gets the new_password2 of this PasswordChange.  # noqa: E501


        :return: The new_password2 of this PasswordChange.  # noqa: E501
        :rtype: str
        """
        return self._new_password2

    @new_password2.setter
    def new_password2(self, new_password2):
        """Sets the new_password2 of this PasswordChange.


        :param new_password2: The new_password2 of this PasswordChange.  # noqa: E501
        :type: str
        """
        if new_password2 is None:
            raise ValueError(
                "Invalid value for `new_password2`, must not be `None`"
            )  # noqa: E501

        self._new_password2 = new_password2

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(
                        lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                        value,
                    )
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(PasswordChange, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PasswordChange):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
