# coding: utf-8

"""
    CVAT REST API

    REST API for Computer Vision Annotation Tool (CVAT)  # noqa: E501

    OpenAPI spec version: v1
    Contact: nikita.manovich@intel.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class LogEvent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "job_id": "int",
        "task_id": "int",
        "proj_id": "int",
        "client_id": "int",
        "name": "str",
        "time": "datetime",
        "message": "str",
        "payload": "dict(str, str)",
        "is_active": "bool",
    }

    attribute_map = {
        "job_id": "job_id",
        "task_id": "task_id",
        "proj_id": "proj_id",
        "client_id": "client_id",
        "name": "name",
        "time": "time",
        "message": "message",
        "payload": "payload",
        "is_active": "is_active",
    }

    def __init__(
        self,
        job_id=None,
        task_id=None,
        proj_id=None,
        client_id=None,
        name=None,
        time=None,
        message=None,
        payload=None,
        is_active=None,
    ):  # noqa: E501
        """LogEvent - a model defined in Swagger"""  # noqa: E501
        self._job_id = None
        self._task_id = None
        self._proj_id = None
        self._client_id = None
        self._name = None
        self._time = None
        self._message = None
        self._payload = None
        self._is_active = None
        self.discriminator = None
        if job_id is not None:
            self.job_id = job_id
        if task_id is not None:
            self.task_id = task_id
        if proj_id is not None:
            self.proj_id = proj_id
        self.client_id = client_id
        self.name = name
        self.time = time
        if message is not None:
            self.message = message
        if payload is not None:
            self.payload = payload
        self.is_active = is_active

    @property
    def job_id(self):
        """Gets the job_id of this LogEvent.  # noqa: E501


        :return: The job_id of this LogEvent.  # noqa: E501
        :rtype: int
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this LogEvent.


        :param job_id: The job_id of this LogEvent.  # noqa: E501
        :type: int
        """

        self._job_id = job_id

    @property
    def task_id(self):
        """Gets the task_id of this LogEvent.  # noqa: E501


        :return: The task_id of this LogEvent.  # noqa: E501
        :rtype: int
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this LogEvent.


        :param task_id: The task_id of this LogEvent.  # noqa: E501
        :type: int
        """

        self._task_id = task_id

    @property
    def proj_id(self):
        """Gets the proj_id of this LogEvent.  # noqa: E501


        :return: The proj_id of this LogEvent.  # noqa: E501
        :rtype: int
        """
        return self._proj_id

    @proj_id.setter
    def proj_id(self, proj_id):
        """Sets the proj_id of this LogEvent.


        :param proj_id: The proj_id of this LogEvent.  # noqa: E501
        :type: int
        """

        self._proj_id = proj_id

    @property
    def client_id(self):
        """Gets the client_id of this LogEvent.  # noqa: E501


        :return: The client_id of this LogEvent.  # noqa: E501
        :rtype: int
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this LogEvent.


        :param client_id: The client_id of this LogEvent.  # noqa: E501
        :type: int
        """
        if client_id is None:
            raise ValueError(
                "Invalid value for `client_id`, must not be `None`"
            )  # noqa: E501

        self._client_id = client_id

    @property
    def name(self):
        """Gets the name of this LogEvent.  # noqa: E501


        :return: The name of this LogEvent.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LogEvent.


        :param name: The name of this LogEvent.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501

        self._name = name

    @property
    def time(self):
        """Gets the time of this LogEvent.  # noqa: E501


        :return: The time of this LogEvent.  # noqa: E501
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this LogEvent.


        :param time: The time of this LogEvent.  # noqa: E501
        :type: datetime
        """
        if time is None:
            raise ValueError(
                "Invalid value for `time`, must not be `None`"
            )  # noqa: E501

        self._time = time

    @property
    def message(self):
        """Gets the message of this LogEvent.  # noqa: E501


        :return: The message of this LogEvent.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this LogEvent.


        :param message: The message of this LogEvent.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def payload(self):
        """Gets the payload of this LogEvent.  # noqa: E501


        :return: The payload of this LogEvent.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this LogEvent.


        :param payload: The payload of this LogEvent.  # noqa: E501
        :type: dict(str, str)
        """

        self._payload = payload

    @property
    def is_active(self):
        """Gets the is_active of this LogEvent.  # noqa: E501


        :return: The is_active of this LogEvent.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this LogEvent.


        :param is_active: The is_active of this LogEvent.  # noqa: E501
        :type: bool
        """
        if is_active is None:
            raise ValueError(
                "Invalid value for `is_active`, must not be `None`"
            )  # noqa: E501

        self._is_active = is_active

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(
                        lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                        value,
                    )
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(LogEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LogEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
