# coding: utf-8

"""
    CVAT REST API

    REST API for Computer Vision Annotation Tool (CVAT)  # noqa: E501

    OpenAPI spec version: v1
    Contact: nikita.manovich@intel.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.server_api import ServerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServerApi(unittest.TestCase):
    """ServerApi unit test stubs"""

    def setUp(self):
        self.api = ServerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_server_about(self):
        """Test case for server_about

        Method provides basic CVAT information  # noqa: E501
        """
        pass

    def test_server_annotation_annotation_formats(self):
        """Test case for server_annotation_annotation_formats

        Method provides the list of supported annotations formats  # noqa: E501
        """
        pass

    def test_server_exception(self):
        """Test case for server_exception

        Saves an exception from a client on the server  # noqa: E501
        """
        pass

    def test_server_logs(self):
        """Test case for server_logs

        Saves logs from a client on the server  # noqa: E501
        """
        pass

    def test_server_plugins(self):
        """Test case for server_plugins

        Method provides allowed plugins.  # noqa: E501
        """
        pass

    def test_server_share(self):
        """Test case for server_share

        Returns all files and folders that are on the server along specified path  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
