# coding: utf-8

"""
    CVAT REST API

    REST API for Computer Vision Annotation Tool (CVAT)  # noqa: E501

    OpenAPI spec version: v1
    Contact: nikita.manovich@intel.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.predict_api import PredictApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPredictApi(unittest.TestCase):
    """PredictApi unit test stubs"""

    def setUp(self):
        self.api = PredictApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_predict_predict_image(self):
        """Test case for predict_predict_image

        Returns prediction for image  # noqa: E501
        """
        pass

    def test_predict_predict_status(self):
        """Test case for predict_predict_status

        Returns information of the tasks of the project with the selected id  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
