# coding: utf-8

"""
    CVAT REST API

    REST API for Computer Vision Annotation Tool (CVAT)  # noqa: E501

    OpenAPI spec version: v1
    Contact: nikita.manovich@intel.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cloud_storages_api import (  # noqa: E501
    CloudStoragesApi,
)
from swagger_client.rest import ApiException


class TestCloudStoragesApi(unittest.TestCase):
    """CloudStoragesApi unit test stubs"""

    def setUp(self):
        self.api = CloudStoragesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cloudstorages_content(self):
        """Test case for cloudstorages_content

        Method returns a manifest content  # noqa: E501
        """
        pass

    def test_cloudstorages_create(self):
        """Test case for cloudstorages_create

        Method creates a cloud storage with a specified characteristics  # noqa: E501
        """
        pass

    def test_cloudstorages_delete(self):
        """Test case for cloudstorages_delete

        Method deletes a specific cloud storage  # noqa: E501
        """
        pass

    def test_cloudstorages_list(self):
        """Test case for cloudstorages_list

        Returns a paginated list of storages according to query parameters  # noqa: E501
        """
        pass

    def test_cloudstorages_partial_update(self):
        """Test case for cloudstorages_partial_update

        Methods does a partial update of chosen fields in a cloud storage instance  # noqa: E501
        """
        pass

    def test_cloudstorages_preview(self):
        """Test case for cloudstorages_preview

        Method returns a preview image from a cloud storage  # noqa: E501
        """
        pass

    def test_cloudstorages_read(self):
        """Test case for cloudstorages_read

        Method returns details of a specific cloud storage  # noqa: E501
        """
        pass

    def test_cloudstorages_status(self):
        """Test case for cloudstorages_status

        Method returns a cloud storage status  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
