# coding: utf-8

"""
    CVAT REST API

    REST API for Computer Vision Annotation Tool (CVAT)  # noqa: E501

    OpenAPI spec version: v1
    Contact: nikita.manovich@intel.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.auth_signing_body import (  # noqa: E501
    AuthSigningBody,
)
from swagger_client.rest import ApiException


class TestAuthSigningBody(unittest.TestCase):
    """AuthSigningBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthSigningBody(self):
        """Test AuthSigningBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.auth_signing_body.AuthSigningBody()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
