# coding: utf-8

"""
    CVAT REST API

    REST API for Computer Vision Annotation Tool (CVAT)  # noqa: E501

    OpenAPI spec version: v1
    Contact: nikita.manovich@intel.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.server_file import ServerFile  # noqa: E501
from swagger_client.rest import ApiException


class TestServerFile(unittest.TestCase):
    """ServerFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerFile(self):
        """Test ServerFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.server_file.ServerFile()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
