# coding: utf-8

"""
    CVAT REST API

    REST API for Computer Vision Annotation Tool (CVAT)  # noqa: E501

    OpenAPI spec version: v1
    Contact: nikita.manovich@intel.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.projects_api import ProjectsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_projects_annotations(self):
        """Test case for projects_annotations

        Method allows to download project annotations  # noqa: E501
        """
        pass

    def test_projects_create(self):
        """Test case for projects_create

        Method creates a new project  # noqa: E501
        """
        pass

    def test_projects_dataset_export(self):
        """Test case for projects_dataset_export

        Export project as a dataset in a specific format  # noqa: E501
        """
        pass

    def test_projects_delete(self):
        """Test case for projects_delete

        Method deletes a specific project  # noqa: E501
        """
        pass

    def test_projects_list(self):
        """Test case for projects_list

        Returns a paginated list of projects according to query parameters (12 projects per page)  # noqa: E501
        """
        pass

    def test_projects_partial_update(self):
        """Test case for projects_partial_update

        Methods does a partial update of chosen fields in a project  # noqa: E501
        """
        pass

    def test_projects_read(self):
        """Test case for projects_read

        Method returns details of a specific project  # noqa: E501
        """
        pass

    def test_projects_tasks(self):
        """Test case for projects_tasks

        Returns information of the tasks of the project with the selected id  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
