# coding: utf-8

"""
    CVAT REST API

    REST API for Computer Vision Annotation Tool (CVAT)  # noqa: E501

    OpenAPI spec version: v1
    Contact: nikita.manovich@intel.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.comments_api import CommentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCommentsApi(unittest.TestCase):
    """CommentsApi unit test stubs"""

    def setUp(self):
        self.api = CommentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_comments_create(self):
        """Test case for comments_create

        """
        pass

    def test_comments_delete(self):
        """Test case for comments_delete

        Method removes a comment from an issue  # noqa: E501
        """
        pass

    def test_comments_partial_update(self):
        """Test case for comments_partial_update

        Method updates comment in an issue  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
