# Common parameters for training representation models.

# Path to the folder containing the MARS images.
mars_image_folder: data/05_model_input/mars_multi_camera_boll_synthetic

# Number of epochs to train for.
num_epochs: 100
# Learning rate to use for training.
learning_rate: 0.001
# Temperature parameter to use for the loss.
temperature: 0.07

# Whether to use MoCo. Otherwise, will use normal SimCLR.
use_moco: true
# Whether to use contrastive crop. Otherwise, it will use normal random
# cropping.
contrastive_crop: false
# Whether to fine-tune the backbone instead of fully re-training it.
finetune_backbone: false
# Whether to enable data augmentation on the individual views.
augment_views: false
