# Amount of temporal jitter to apply to frame selections.
max_frame_jitter: 0
# Whether to enable multi-camera training. Otherwise, it will use
# vanilla SimCLR.
enable_multi_view: false
# Limit training to these specific views.
filter_views: [0, 1, 2, 3, 4]
# Select this many views for each example.
num_views: 2
# Add this many extra temporal views for each example.
num_temporal_views: 0
# Number of examples to use from the dataset.
downsample_size: 192000
