# Path to the folder containing the MARS images.
mars_image_folder: data/05_model_input/mars_multi_camera

# Number of epochs to train for.
num_epochs: 100
# Learning rate to use for training.
learning_rate: 0.001

# Entity to use for WandB. Should be your username or team name.
wandb_entity: djpetti
