# Path to the folder containing the MARS images.
mars_image_folder: data/05_model_input/mars_multi_camera

# Number of epochs to train for.
simclr_num_epochs: 100
# Learning rate to use for training.
simclr_learning_rate: 0.001
# Temperature parameter to use for the loss.
simclr_temperature: 0.1
